services:
    # PHP Service (Laravel Console App)
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            - laravel
        command: php artisan generate-report  # default command to run when the container starts

    # Test Runner
    test:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_test
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - laravel
        entrypoint: ["php", "vendor/bin/pest"] # runs Pest tests

networks:
    laravel:
